### ISSUE TITLE
Fluorine no longer loads latest replay on startup even when the monitor option is enabled

### ISSUE THREAD

**Issue by rlee287** [fohristiwhirl/fluorine#20]
In previous versions (v1.2.4), starting up Fluorine with the monitor option on would automatically load the latest replay in that folder. This is no longer the case on master (e83d993).

This has been `git bisect`ed to eead1b47044ccfb5f6d3294bfd63e23a9ef7615a as the first "bad" commit with this behavior.

**Comment by fohristiwhirl** [comment]
Restored in f67f988 though I'm still worried about performance. I changed it from a functional thing with map and filter and so on to something more straightforward but I expect it's the OS itself that causes most of the delay...
