### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by timjolson** [fohristiwhirl/fluorine#22]
When opening Fluorine, in 'dev tools' I'm consistently receiving

> Uncaught ReferenceError: require is not defined
at fluorine.renderer.js: 3

npm -v  -> 6.4.1
node -v  -> v10.15.3
Ubuntu  -> 18.04

Possibly [related](https://requirejs.org/docs/node.html)
Obviously this is low priority without an on-going competition, but this is just a heads-up.

![Screenshot from 2019-05-10 16-57-28](https://user-images.githubusercontent.com/5532473/57559039-a59d5500-7345-11e9-8259-f80015d6795c.png)

**Comment by fohristiwhirl** [comment]
I'm guessing this is new in Electron 5, or something.

**Comment by fohristiwhirl** [comment]
My PC's currently in a fairly poor state for dev work - can you try changing [this line](https://github.com/fohristiwhirl/fluorine/blob/master/modules/windows.js#L32) to read:

```javascript
webPreferences: {zoomFactor: zoom_factor, nodeIntegration: true}
```

And let me know?

**Comment by timjolson** [comment]
That worked
