### ISSUE TITLE
Ubuntu 16.04 keyboard doesn't work

### ISSUE THREAD

**Issue by WatsOne** [fohristiwhirl/fluorine#6]
App doesn't react on any key press

**Comment by fohristiwhirl** [comment]
Hmm. That's annoying. I've 2 reports of it working on 18.04 so I'm not sure what the problem here would be.

**Comment by fohristiwhirl** [comment]
I don't suppose there's any info in the dev tools? ("Extra" menu, then console tab...)

**Comment by WatsOne** [comment]
There are two message in console:
Couldn't read prefs. fluorine_renderer.html:879 
and
Electron Security Warning (Insecure Content-Security-Policy). This renderer process has either no Content Security
      Policy set or a policy with "unsafe-eval" enabled.

**Comment by WatsOne** [comment]
Yeah, on 18.04 Ubuntu keys work correct.

**Comment by fohristiwhirl** [comment]
What version of Electron are you using?

**Comment by WatsOne** [comment]
3.0.4

**Comment by WatsOne** [comment]
Unfortunately, I have already updated my Ubuntu to 18.04 (I was going to do this for a long time, but I didn’t have time), and bug disappeared as expected... 
So, I think this issue can be closed till anybody can reproduce it.
Thanks for your help and thanks for the amazing tool!

**Comment by fohristiwhirl** [comment]
Alright, thanks.
